### ISSUE TITLE
cargo xtask run fails on Debian ARM64

### ISSUE THREAD

**Issue by alessandromrc** [aya-rs/aya-template#116]
Stack Trace:
```
alessandro@debian:~/projects/demo$ RUST_BACKTRACE=full RUST_LOG=info cargo xtask run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/xtask run`
   Compiling demo-ebpf v0.1.0 (/home/alessandro/projects/demo/demo-ebpf)
error: linking with `bpf-linker` failed: signal: 6 (SIGABRT)
  |
  = note: LC_ALL="C" PATH="/home/alessandro/.rustup/toolchains/nightly-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/bin:/home/alessandro/.rustup/toolchains/nightly-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/bin:/home/alessandro/.rustup/toolchains/nightly-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/bin:/home/alessandro/.cargo/bin:/home/alessandro/.vscode-server-insiders/cli/servers/Insiders-e34ecab75b0c379c17921f759a77eebaf24bebf2/server/bin/remote-cli:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/sbin:/usr/sbin" VSLANG="1033" "bpf-linker" "--export-symbols" "/tmp/rustcox1Y0F/symbols" "/tmp/rustcox1Y0F/symbols.o" "/home/alessandro/projects/demo/demo-ebpf/../target/bpfel-unknown-none/debug/deps/demo-c34a50b77618dbd5.demo.8027547daa8f8826-cgu.0.rcgu.o" "--cpu" "generic" "-o" "/home/alessandro/projects/demo/demo-ebpf/../target/bpfel-unknown-none/debug/deps/demo-c34a50b77618dbd5" "-O3" "--debug"
  = note: INFO command line: "bpf-linker --export-symbols /tmp/rustcox1Y0F/symbols /tmp/rustcox1Y0F/symbols.o /home/alessandro/projects/demo/demo-ebpf/../target/bpfel-unknown-none/debug/deps/demo-c34a50b77618dbd5.demo.8027547daa8f8826-cgu.0.rcgu.o --cpu generic -o /home/alessandro/projects/demo/demo-ebpf/../target/bpfel-unknown-none/debug/deps/demo-c34a50b77618dbd5 -O3 --debug"
          INFO LLVM command line: ["bpf-linker", "--cold-callsite-rel-freq=0", "--bpf-expand-memcpy-in-order"]
          unable to read dir /home/alessandro/.cargo/lib: No such file or directory (os error 2)
          unable to read dir /home/alessandro/.vscode-server-insiders/cli/servers/Insiders-e34ecab75b0c379c17921f759a77eebaf24bebf2/server/bin/lib: No such file or directory (os error 2)
          thread 'main' panicked at /home/alessandro/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aya-rustc-llvm-proxy-0.9.3/src/lib.rs:102:5:
          unable to find LLVM shared lib
          stack backtrace:
             0:     0xaaaac247bb9c - std::backtrace_rs::backtrace::libunwind::trace::h478edc47103e3f06
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
             1:     0xaaaac247bb9c - std::backtrace_rs::backtrace::trace_unsynchronized::h42581fa4d7d2711f
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
             2:     0xaaaac247bb9c - std::sys::backtrace::_print_fmt::hfa792f5d727892f7
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:65:5
             3:     0xaaaac247bb9c - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hd1bd86f9e87f2dc6
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:40:26
             4:     0xaaaac249a8d4 - core::fmt::rt::Argument::fmt::h4994c882fc039333
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/fmt/rt.rs:173:76
             5:     0xaaaac249a8d4 - core::fmt::write::hf784ddce2439beb2
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/fmt/mod.rs:1182:21
             6:     0xaaaac24794b4 - std::io::Write::write_fmt::h3a532ab2ed2a81ef
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/io/mod.rs:1827:15
             7:     0xaaaac247cd58 - std::sys::backtrace::BacktraceLock::print::h3dc3d1eeb242dea4
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:43:9
             8:     0xaaaac247cd58 - std::panicking::default_hook::{{closure}}::hdf566474624f0305
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:269:22
             9:     0xaaaac247c938 - std::panicking::default_hook::h7eca74c8246bec15
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:296:9
            10:     0xaaaac247d370 - std::panicking::rust_panic_with_hook::h23f33ab5bab293ef
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:800:13
            11:     0xaaaac247d150 - std::panicking::begin_panic_handler::{{closure}}::h8ea86e6103cb361c
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:667:13
            12:     0xaaaac247c084 - std::sys::backtrace::__rust_end_short_backtrace::h6e01bce97227982e
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:168:18
            13:     0xaaaac247ce48 - rust_begin_unwind
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
            14:     0xaaaac2311c48 - core::panicking::panic_fmt::hb1e0b874c9a3c491
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
            15:     0xaaaac245bf20 - aya_rustc_llvm_proxy::SHARED_LIB::{{closure}}::h7b4d45ff320c8474
                                         at /home/alessandro/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aya-rustc-llvm-proxy-0.9.3/src/lib.rs:102:5
            16:     0xaaaac245bf20 - core::ops::function::FnOnce::call_once::hecf6bd43d578a0b4
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
            17:     0xaaaac245c3a0 - core::ops::function::FnOnce::call_once::h62f9189872d1af5c
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
            18:     0xaaaac245c3a0 - once_cell::sync::Lazy<T,F>::force::{{closure}}::h6431eeedb2a726b6
                                         at /home/alessandro/.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.19.0/src/lib.rs:1310:28
            19:     0xaaaac245c3a0 - once_cell::sync::OnceCell<T>::get_or_init::{{closure}}::h95734195212067e1
                                         at /home/alessandro/.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.19.0/src/lib.rs:1120:57
            20:     0xaaaac245c3a0 - once_cell::imp::OnceCell<T>::initialize::{{closure}}::h9aa90107edbf07cf
                                         at /home/alessandro/.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.19.0/src/imp_std.rs:72:23
            21:     0xaaaac245c90c - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::hf1eac24132d62ae1
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:294:13
            22:     0xaaaac245c90c - once_cell::imp::initialize_or_wait::h506e0421ad6800d4
                                         at /home/alessandro/.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.19.0/src/imp_std.rs:196:20
            23:     0xaaaac230fbe0 - once_cell::imp::OnceCell<T>::initialize::h811d06ded2876093
                                         at /home/alessandro/.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.19.0/src/imp_std.rs:68:9
            24:     0xaaaac245a350 - once_cell::sync::OnceCell<T>::get_or_try_init::hf5476d446b3af6a6
                                         at /home/alessandro/.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.19.0/src/lib.rs:1161:13
            25:     0xaaaac245a350 - once_cell::sync::OnceCell<T>::get_or_init::ha52676310b461eca
                                         at /home/alessandro/.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.19.0/src/lib.rs:1120:19
            26:     0xaaaac245a350 - once_cell::sync::Lazy<T,F>::force::hd4580f7d370c6aa5
                                         at /home/alessandro/.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.19.0/src/lib.rs:1309:23
            27:     0xaaaac245a350 - <once_cell::sync::Lazy<T,F> as core::ops::deref::Deref>::deref::h97f8f91a066104c0
                                         at /home/alessandro/.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.19.0/src/lib.rs:1376:13
            28:     0xaaaac245a350 - LLVMInitializeBPFTarget
                                         at /tmp/cargo-installv3Wisb/release/build/aya-rustc-llvm-proxy-7ba69a8c9db72362/out/llvm_gen.rs:13972:9
            29:     0xaaaac244af08 - bpf_linker::llvm::init::ha1d83dca9d0715e0
                                         at /home/alessandro/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bpf-linker-0.9.13/src/llvm/mod.rs:56:5
            30:     0xaaaac2444a4c - bpf_linker::linker::Linker::llvm_init::h6c2947dbf7b0d303
                                         at /home/alessandro/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bpf-linker-0.9.13/src/linker.rs:535:13
            31:     0xaaaac2444a4c - bpf_linker::linker::Linker::link::hcaef28ecde2d9a23
                                         at /home/alessandro/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bpf-linker-0.9.13/src/linker.rs:249:9
            32:     0xaaaac2340894 - bpf_linker::main::h18682a17fb8b3a08
                                         at /home/alessandro/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bpf-linker-0.9.13/src/bin/bpf-linker.rs:303:5
            33:     0xaaaac2347b60 - core::ops::function::FnOnce::call_once::h656d11a4378f7a26
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
            34:     0xaaaac2347b60 - std::sys::backtrace::__rust_begin_short_backtrace::h975fd0d0f70e07e9
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:152:18
            35:     0xaaaac23359ec - std::rt::lang_start::{{closure}}::ha708cb815f59ef3e
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/rt.rs:162:18
            36:     0xaaaac24737cc - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hc83e0360677e1061
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:284:13
            37:     0xaaaac24737cc - std::panicking::try::do_call::hcec7ace625a1aaf6
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:557:40
            38:     0xaaaac24737cc - std::panicking::try::h32c52e107e411c58
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:521:19
            39:     0xaaaac24737cc - std::panic::catch_unwind::hd88646b290a0ace7
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panic.rs:350:14
            40:     0xaaaac24737cc - std::rt::lang_start_internal::{{closure}}::h2005ed25137ce85a
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/rt.rs:141:48
            41:     0xaaaac24737cc - std::panicking::try::do_call::h471ef3d560f3540d
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:557:40
            42:     0xaaaac24737cc - std::panicking::try::h81d64da2a2c5a1cf
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:521:19
            43:     0xaaaac24737cc - std::panic::catch_unwind::ha54838b763989a8d
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panic.rs:350:14
            44:     0xaaaac24737cc - std::rt::lang_start_internal::h69e5a956edcf8a00
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/rt.rs:141:20
            45:     0xaaaac2347304 - main
            46:     0xffff8fbc7740 - <unknown>
            47:     0xffff8fbc7818 - __libc_start_main
            48:     0xaaaac23122b0 - _start
            49:                0x0 - <unknown>
          thread 'main' panicked at library/core/src/panicking.rs:221:5:
          panic in a function that cannot unwind
          stack backtrace:
             0:     0xaaaac247bb9c - std::backtrace_rs::backtrace::libunwind::trace::h478edc47103e3f06
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
             1:     0xaaaac247bb9c - std::backtrace_rs::backtrace::trace_unsynchronized::h42581fa4d7d2711f
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
             2:     0xaaaac247bb9c - std::sys::backtrace::_print_fmt::hfa792f5d727892f7
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:65:5
             3:     0xaaaac247bb9c - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hd1bd86f9e87f2dc6
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:40:26
             4:     0xaaaac249a8d4 - core::fmt::rt::Argument::fmt::h4994c882fc039333
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/fmt/rt.rs:173:76
             5:     0xaaaac249a8d4 - core::fmt::write::hf784ddce2439beb2
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/fmt/mod.rs:1182:21
             6:     0xaaaac24794b4 - std::io::Write::write_fmt::h3a532ab2ed2a81ef
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/io/mod.rs:1827:15
             7:     0xaaaac247cd58 - std::sys::backtrace::BacktraceLock::print::h3dc3d1eeb242dea4
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:43:9
             8:     0xaaaac247cd58 - std::panicking::default_hook::{{closure}}::hdf566474624f0305
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:269:22
             9:     0xaaaac247c938 - std::panicking::default_hook::h7eca74c8246bec15
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:296:9
            10:     0xaaaac247d370 - std::panicking::rust_panic_with_hook::h23f33ab5bab293ef
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:800:13
            11:     0xaaaac247d150 - std::panicking::begin_panic_handler::{{closure}}::h8ea86e6103cb361c
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:667:13
            12:     0xaaaac247c084 - std::sys::backtrace::__rust_end_short_backtrace::h6e01bce97227982e
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:168:18
            13:     0xaaaac247ce48 - rust_begin_unwind
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
            14:     0xaaaac2311c78 - core::panicking::panic_nounwind_fmt::runtime::h38472b51f7eca294
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:112:18
            15:     0xaaaac2311c78 - core::panicking::panic_nounwind_fmt::h01b437f4a97f4346
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:122:5
            16:     0xaaaac2311cf0 - core::panicking::panic_nounwind::h17298cd3cbc2905e
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:221:5
            17:     0xaaaac2311d94 - core::panicking::panic_cannot_unwind::hd0e9c6802cc1dd3d
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:309:5
            18:     0xaaaac245a3d4 - LLVMInitializeBPFTarget
                                         at /tmp/cargo-installv3Wisb/release/build/aya-rustc-llvm-proxy-7ba69a8c9db72362/out/llvm_gen.rs:13970:1
            19:     0xaaaac244af08 - bpf_linker::llvm::init::ha1d83dca9d0715e0
                                         at /home/alessandro/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bpf-linker-0.9.13/src/llvm/mod.rs:56:5
            20:     0xaaaac2444a4c - bpf_linker::linker::Linker::llvm_init::h6c2947dbf7b0d303
                                         at /home/alessandro/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bpf-linker-0.9.13/src/linker.rs:535:13
            21:     0xaaaac2444a4c - bpf_linker::linker::Linker::link::hcaef28ecde2d9a23
                                         at /home/alessandro/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bpf-linker-0.9.13/src/linker.rs:249:9
            22:     0xaaaac2340894 - bpf_linker::main::h18682a17fb8b3a08
                                         at /home/alessandro/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bpf-linker-0.9.13/src/bin/bpf-linker.rs:303:5
            23:     0xaaaac2347b60 - core::ops::function::FnOnce::call_once::h656d11a4378f7a26
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
            24:     0xaaaac2347b60 - std::sys::backtrace::__rust_begin_short_backtrace::h975fd0d0f70e07e9
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:152:18
            25:     0xaaaac23359ec - std::rt::lang_start::{{closure}}::ha708cb815f59ef3e
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/rt.rs:162:18
            26:     0xaaaac24737cc - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hc83e0360677e1061
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:284:13
            27:     0xaaaac24737cc - std::panicking::try::do_call::hcec7ace625a1aaf6
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:557:40
            28:     0xaaaac24737cc - std::panicking::try::h32c52e107e411c58
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:521:19
            29:     0xaaaac24737cc - std::panic::catch_unwind::hd88646b290a0ace7
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panic.rs:350:14
            30:     0xaaaac24737cc - std::rt::lang_start_internal::{{closure}}::h2005ed25137ce85a
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/rt.rs:141:48
            31:     0xaaaac24737cc - std::panicking::try::do_call::h471ef3d560f3540d
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:557:40
            32:     0xaaaac24737cc - std::panicking::try::h81d64da2a2c5a1cf
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:521:19
            33:     0xaaaac24737cc - std::panic::catch_unwind::ha54838b763989a8d
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panic.rs:350:14
            34:     0xaaaac24737cc - std::rt::lang_start_internal::h69e5a956edcf8a00
                                         at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/rt.rs:141:20
            35:     0xaaaac2347304 - main
            36:     0xffff8fbc7740 - <unknown>
            37:     0xffff8fbc7818 - __libc_start_main
            38:     0xaaaac23122b0 - _start
            39:                0x0 - <unknown>
          thread caused non-unwinding panic. aborting.
          

error: could not compile `demo-ebpf` (bin "demo") due to 1 previous error
thread 'main' panicked at xtask/src/build_ebpf.rs:65:5:
assertion failed: status.success()
stack backtrace:
   0:     0xaaaabfbd11dc - std::backtrace_rs::backtrace::libunwind::trace::h478edc47103e3f06
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0xaaaabfbd11dc - std::backtrace_rs::backtrace::trace_unsynchronized::h42581fa4d7d2711f
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0xaaaabfbd11dc - std::sys::backtrace::_print_fmt::hfa792f5d727892f7
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:65:5
   3:     0xaaaabfbd11dc - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hd1bd86f9e87f2dc6
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:40:26
   4:     0xaaaabfbed15c - core::fmt::rt::Argument::fmt::h4994c882fc039333
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/fmt/rt.rs:173:76
   5:     0xaaaabfbed15c - core::fmt::write::hf784ddce2439beb2
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/fmt/mod.rs:1182:21
   6:     0xaaaabfbcf0e4 - std::io::Write::write_fmt::h3a532ab2ed2a81ef
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/io/mod.rs:1827:15
   7:     0xaaaabfbd2750 - std::sys::backtrace::BacktraceLock::print::h3dc3d1eeb242dea4
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:43:9
   8:     0xaaaabfbd2750 - std::panicking::default_hook::{{closure}}::hdf566474624f0305
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:269:22
   9:     0xaaaabfbd2330 - std::panicking::default_hook::h7eca74c8246bec15
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:296:9
  10:     0xaaaabfbd2cb0 - std::panicking::rust_panic_with_hook::h23f33ab5bab293ef
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:800:13
  11:     0xaaaabfbd2b48 - std::panicking::begin_panic_handler::{{closure}}::h8ea86e6103cb361c
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:667:13
  12:     0xaaaabfbd16c4 - std::sys::backtrace::__rust_end_short_backtrace::h6e01bce97227982e
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:168:18
  13:     0xaaaabfbd2840 - rust_begin_unwind
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
  14:     0xaaaabfa9fca0 - core::panicking::panic_fmt::hb1e0b874c9a3c491
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
  15:     0xaaaabfa9fd0c - core::panicking::panic::hefd0c09c6ada38da
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:148:5
  16:     0xaaaabfaa24cc - xtask::build_ebpf::build_ebpf::hdd4264de40fbd9c9
                               at /home/alessandro/projects/demo/xtask/src/build_ebpf.rs:65:5
  17:     0xaaaabfaa0f94 - xtask::build::build::h865b53b265aa2fc0
                               at /home/alessandro/projects/demo/xtask/src/build.rs:35:5
  18:     0xaaaabfaad5a4 - xtask::run::run::h3cc0f5b23f76c463
                               at /home/alessandro/projects/demo/xtask/src/run.rs:28:5
  19:     0xaaaabfaa9178 - xtask::main::hdf30cd339d565123
                               at /home/alessandro/projects/demo/xtask/src/main.rs:28:22
  20:     0xaaaabfab1d90 - core::ops::function::FnOnce::call_once::h32eae3f976a38237
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
  21:     0xaaaabfaafd44 - std::sys::backtrace::__rust_begin_short_backtrace::h32708628f26aa360
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:152:18
  22:     0xaaaabfab5398 - std::rt::lang_start::{{closure}}::h438b936f11ec3226
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/rt.rs:162:18
  23:     0xaaaabfbc9e0c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hc83e0360677e1061
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:284:13
  24:     0xaaaabfbc9e0c - std::panicking::try::do_call::hcec7ace625a1aaf6
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:557:40
  25:     0xaaaabfbc9e0c - std::panicking::try::h32c52e107e411c58
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:521:19
  26:     0xaaaabfbc9e0c - std::panic::catch_unwind::hd88646b290a0ace7
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panic.rs:350:14
  27:     0xaaaabfbc9e0c - std::rt::lang_start_internal::{{closure}}::h2005ed25137ce85a
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/rt.rs:141:48
  28:     0xaaaabfbc9e0c - std::panicking::try::do_call::h471ef3d560f3540d
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:557:40
  29:     0xaaaabfbc9e0c - std::panicking::try::h81d64da2a2c5a1cf
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:521:19
  30:     0xaaaabfbc9e0c - std::panic::catch_unwind::ha54838b763989a8d
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panic.rs:350:14
  31:     0xaaaabfbc9e0c - std::rt::lang_start_internal::h69e5a956edcf8a00
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/rt.rs:141:20
  32:     0xaaaabfab5368 - std::rt::lang_start::hc2df38243132f7ff
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/rt.rs:161:17
  33:     0xaaaabfaa9d2c - main
  34:     0xffff870a7740 - <unknown>
  35:     0xffff870a7818 - __libc_start_main
  36:     0xaaaabfaa03f0 - _start
  37:                0x0 - <unknown>
```

**Comment by alessandromrc** [comment]
It seems like the LLVM shared lib is not available for ARM64 for some reasons, I tried to match install the version 19 but some dependencies are also not available on ARM as it seems.

**Comment by alessandrod** [comment]
Which dependencies are not available? I use arm64 as my main dev machine

**Comment by alessandromrc** [comment]
It seemed like I wasn't able to get llvm-19 to work but I am not sure about what the problem was (Rust) wise since I pretty much never used it.

I was following this guide here: https://konghq.com/blog/engineering/writing-an-ebpf-xdp-load-balancer-in-rust
